### PR TITLE
#216 `iteratefdtd_matrix`: Updates for the main loop

### LINKED ISSUE #216: Update to `iteratefdtd_matrix`: Main Loop Alterations
Subtask of #208 |

### Main Loop Alterations

These changes are rather self contained, and do not require any major reworking of the current test framework or how `tdms` behaves on the command line. _Where_ in the codebase these changes occur will be in either `execute_simulation` or `simulation.execute`, depending on post or pre #215.

- [ ] Whenever `{I,J,K}_source` is non-empty, the corresponding field update lines in the main loop need to be executed. These are a subsection of lines [2121 through 2231](https://github.com/UCL/TDMS/blob/384a91ab8d0b24bc2d48233d710d2f4e4cf14f64/tdms/src/simulation_manager/execute_simulation.cpp#L2121-L2231).
- [ ] If all `{I,J,K}_source` are non-empty, then outputs should not be normalised. The functions listed in the issue have been superseded by class methods, with the lines not to be executed being [here](https://github.com/UCL/TDMS/blob/1924201bdad21465f6aa05677b4294eed7993832/tdms/src/iterator.cpp#L4222-L4242) (or in the `post_loop_processing()` method if [PR215](https://github.com/UCL/TDMS/pull/215) is merged). 

#### To clarify:
- There is already conditional logic surrounding each part of the codebase to be edited - is the new condition of `{I,J,K}_source` all being empty a replacement, an additional constraint, or an alternative?

### LINKED ISSUE #226: `array_ind` scoping issues
In the `Jsource` loop, the `!inputs.params.is_multilayer`-logical statement occurs within the first `k < inputs.K1.index` conditional statement. 

This is inconsistent with the other loops, where the former is conducted prior to entering the latter conditional block. Additionally, the `array_ind` variable that is assigned in this conditional block is [used again on line 181](https://github.com/UCL/TDMS/blob/10a41b17c6e993f4265c6929366d4f54261f0edb/tdms/src/simulation_manager/source_term_updates.cpp#L150-L181) - despite the fact that it might not actually have been set! 

The logical inconsistency can be seen in [Jsource loop](https://github.com/UCL/TDMS/blob/10a41b17c6e993f4265c6929366d4f54261f0edb/tdms/src/simulation_manager/source_term_updates.cpp#L150-L158) compared to the [Isource loop](https://github.com/UCL/TDMS/blob/10a41b17c6e993f4265c6929366d4f54261f0edb/tdms/src/simulation_manager/source_term_updates.cpp#L25-L34), for example.

### PR DESCRIPTION
**Pull request by willGraham01**
Closes #216 | Continues #63 |

~Diff is large because `.clang-format` is running over all touched files.~ #222 merged so now the diff is manageable.

## `Source` class changes:
- Now tracks whether the source data is empty through the private variable `no_data_stored`. This is safer than relying on comparing the data members `real` and `imag` to `nullptr`, since these are public members and so could be accidentally modified in the codebase. #70 May change this ethos
- Has an access method `is_empty()` that can be used to access `no_data_stored`.

## `ObjectFromInfile` changes:
- Has a fetch-method `all_sources_are_empty()` WDWYTID.

## `SimulationManager` changes:
- `post_processing()` method now only runs the [normalisation lines](https://github.com/UCL/TDMS/blob/d3e838de889c2f71a8797b43b5623972e8fccefd/tdms/src/simulation_manager/simulation_manager.cpp#L69-L76) if at least one of the `Source` inputs is non-empty, as required.

### `source_term_updates.cpp`
New file that breaks off the aforementioned `Source` update equations from the main loop code, and places them into functions. Also involves a logic update and better variable scoping.
- `update_{IJK}source_terms_steadystate()` handles the updates to the `E_s, H_s, J_c, J_s` (as appropriate) in `steadystate` simulations.
- `update_source_steadystate()` serves to unify the update equations, preserving the general structure of the updates whilst using `switch`es to account for differences between the `I,J,K` cases.

## TODO:

- [x] `E_s` `steadystate` update equations
- [x] `E_s` `pulsed` update equations
- [x] `H_s` `steadystate` update equations
- [x] `H_s` `pulsed` update equations
- [x] Resolve flagged issues below

# Issue Resolutions Required
- Impliments the suggestion in #225 - issue remains open for further investigation. 
- This PR now closes #226

### CODE REVIEW

**Comment by samcunliffe** [comment]
> Diff is large because .clang-format is running over all touched files.

Should we, therefore, merge #222 as-is, to simplify(?) this diff? Then `clang-tidy` and/or `cpplint` can come in later pull requests?

**Comment by willGraham01** [comment]
> > Diff is large because .clang-format is running over all touched files.
> 
> Should we, therefore, merge #222 as-is, to simplify(?) this diff? Then `clang-tidy` and/or `cpplint` can come in later pull requests?

Yes - I've made #222 ready for review so it can go in. Then I can rebase/merge this on top of that.

**Review by samcunliffe — COMMENTED** [review]
Sorry for the slow review!
Weirdly I reviewed almost all of this on Monday and... then just stopped(!?)

All looks very good to me. 
`SimulationManager` is now a [large class](https://refactoring.guru/smells/large-class) although that's a big improvement from a gigantonormous function.

**Comment by willGraham01** [comment]
> Sorry for the slow review! Weirdly I reviewed almost all of this on Monday and... then just stopped(!?)
> 
> All looks very good to me. `SimulationManager` is now a [large class](https://refactoring.guru/smells/large-class) although that's a big improvement from a gigantonormous function.

No worries - I've made sufficiently many changes based on your comments that GitHub wants a re-review. Pretty please? :pray:

**Comment by samcunliffe** [comment]
> GitHub wants a re-review

Hm. Interesting. Was browsing the PR rules when looking into automerge but I didn't think I changed anything.
(This is probably my fault.)

**Review by samcunliffe — APPROVED** [review]

**Pull request merged**
