### PR TITLE
Removes the triage directory

### PR DESCRIPTION
**Pull request by t-young31**
Removes all the code in the [triage/](https://github.com/UCL/TDMS/tree/main/triage) directory created when #28 was merged. They don't seem to be needed in the C++ code or matlab scripts but there may be useful functions – thoughts appreciated!

### CODE REVIEW

**Review by giordano — APPROVED** [review]
I'm always happy to remove unused code, but I don't know if this was meant to be used for something else

**Comment by prmunro** [comment]
The following files are useful utilities that aid in setting up simulations and should not be deleted:

triage/calc_dft_norm.m
triage/fdtdduration.m
triage/fdtdlabels.m
triage/fdtdminsteps.m
triage/fdtdminsteps_pstd.m
triage/fdtdts.m

Otherwise, the other files can be deleted.

**Comment by t-young31** [comment]
Thanks for the review @prmunro. Do you have any example of using these functions?

**Comment by prmunro** [comment]
[arc_06.zip](https://github.com/UCL/TDMS/files/9219286/arc_06.zip)
Here is example usage. On closer inspection I recommend the following:

calc_dft_norm.m - delete
fdtdduration.m - retain 
fdtdlabels.m - delete
fdtdminsteps.m - rename to minsteps_fdtd.m
fdtdminsteps_pstd.m - rename to minsteps_pstd.m
fdtdts.m - retain

**Comment by t-young31** [comment]
Thanks! I've added an issue (#56) to test those once #37 has been merged

**Review by prmunro — APPROVED** [review]

**Pull request merged**
